### PR TITLE
Feature 3

### PR DESCRIPTION
**Pull request by Sick-Carlito**
Hi guys, this milestone was meant for the implementation of a "mutual friendship" feature but I sort of had already implemented it in together with what was required on the previous milestone. However, I just added a few tests and a button to the unfriend feature. Please help me find the mistakes in case I have any. Thanks.

### CODE REVIEW

**Comment by Sick-Carlito** [comment]
Hi, since I just started out with capybara, I have added a few tests as required. Also, I have all the stickler configurations as required but somehow the files are not being checked. I've requested another review maybe I'll get some help with that later. Thanks.

**Comment by Sick-Carlito** [comment]
Hi, I've just added a scenario as requested. And on my command line, I'm having 30 tests and they are all passing. Someone please have a look. Thanks.

**Comment by fatymahmed** [comment]
> Hi, I've just added a scenario as requested. And on my command line, I'm having 30 tests and they are all passing. Someone please have a look. Thanks.

I just run the tests and there are 2 that are failing, I'll reach out to you on slack so we can try to fix this.

**Comment by Sick-Carlito** [comment]
Made a few adjustments.

**Comment by Sick-Carlito** [comment]
Sorry, maybe i will do more about the test a little later. Thanks for the suggestion though.

**Comment by Sick-Carlito** [comment]
Thanks people. I can't find the merge button though. Does anybody know how to go about this, please??

**Pull request closed without merging**
