### PR TITLE
MS:5 - Friendship v1

### PR DESCRIPTION
**Pull request by marijanbrvar**
In this milestone, we implemented the following user requirements
- I want to be able to send a friendship invitation.
- I want to see a button “Invite to friendship.” 
- I want to be able to see pending friendship invitations sent to me from other users
- I want to be able to accept or reject friendships' invitation.

We create a model with associations and all requested features for friendships.

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
Nice work meeting most requirements for this PR. A user can signup, send a friend request, confirm/reject requests. Well done.
Let's however make some changes to the PR.
- [ ] Only users who are friends should be able to see their posts. This is currently not working. Please fix that.
- [ ] Add unit and integration tests. Test validation, association logic as well as the ability of a user to signup, create a post, send/accept friend requests (integration tests)


### Martin Afani
#### Slack: whiz25

**Comment by euqueme** [comment]
Hi @marijanbrvar  and @zilton7  :wave:  this is the wrong branch the PR has to be done from your feature branch to your development branch something like this: `marijanbrvar:friendship-v1` into `marijanbrvar:development`

if you already requested another review please :pray: edit this PR description and include the link to the correct PR

I'm closing this :no_entry:

**Comment by marijanbrvar** [comment]
Hi Maria
I am so sorry for producing such a hassle. I see what you are talking g about. Please will you be so kind as to close the current code review for this project. Our current project status is Waiting for review, and I cannot resubmit the new PR again. See picture in attachment. 
Thank you very much, and I am sorry again for my ignorance!

Screen Shot 2021-04-20 at 20 04 59

**Review by andresporras3423 — COMMENTED** [review]
### Status: Changes Required :recycle:
**Hello Zil Norvilis [status: Enrolled] & Marian Brvar** 
Good job with the improvements for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] Add `gem 'tzinfo-data'` to your gemfile
- [ ] Add integration tests to your project

#### OPTIONAL

- Next time, don't close the pull request before approval
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by euqueme** [comment]
@andresporras3423  the students didn't close it I did because it's not following the right flow.

@marijanbrvar please :pray:  make the changes suggested by @andresporras3423  in a new PR that goes from your feature branch to your development branch, do not use this PR again thank you :pray:

**Pull request closed without merging**
