### PR TITLE
Move database from PostgreSQL to sqlite3

### PR DESCRIPTION
**Pull request by ozovalihasan**
PostgreSQL is used for this project, and it needs more configuration than sqlite3. My partner and I used it, but we needed to solve a lot of errors related to PostgreSQL. More, when our project was checked, TSEs got similar errors, and our project was not approved. Using PostgreSQL is time-consuming for both students and TSEs. 
Using sqlite3 as default database provides students to focus on their project and TSEs to check projects quickly. 
Please, merge my changes. If you have any question or another suggestion, let me know it.

Hasan,

### CODE REVIEW

**Comment by ioilmio** [comment]
Hello, sorry to bother you but, are these the errors you got?
ActiveRecord::NoDatabaseError: FATAL:  database "ror_social_scaffold_development" does not exist


Caused by:
PG::ConnectionBad: FATAL:  database "ror_social_scaffold_development" does not exist


Does your changes to files correct them?
I'm in the early phase of this project working alone on it and every help will be helpful;
Thanks in advance

**Comment by fatymahmed** [comment]
> Hello, sorry to bother you but, are these the errors you got?
> ActiveRecord::NoDatabaseError: FATAL: database "ror_social_scaffold_development" does not exist
> 
> Caused by:
> PG::ConnectionBad: FATAL: database "ror_social_scaffold_development" does not exist
> 
> Does your changes to files correct them?
> I'm in the early phase of this project working alone on it and every help will be helpful;
> Thanks in advance

Hi @ioilmio 
It seems that you haven't created the DB
Did you run `rails db:create` then migrate it as explained under the [setup](https://github.com/microverseinc/ror-social-scaffold#setup) instructions in the readme [file](https://github.com/microverseinc/ror-social-scaffold)?

**Comment by fatymahmed** [comment]
> PostgreSQL is used for this project, and it needs more configuration than sqlite3. My partner and I used it, but we needed to solve a lot of errors related to PostgreSQL. More, when our project was checked, TSEs got similar errors, and our project was not approved. Using PostgreSQL is time-consuming for both students and TSEs.
> Using sqlite3 as default database provides students to focus on their project and TSEs to check projects quickly.
> Please, merge my changes. If you have any question or another suggestion, let me know it.
> 
> Hasan,

Thank you for the Pull request and for raising this 🙏.
However, I followed the setup [instructions](https://github.com/microverseinc/ror-social-scaffold#setup) in the readme file and didn't come across any errors, could you provide more information on the errors you got?

**Comment by ozovalihasan** [comment]
Hi @fatymahmed,

I cloned this repository and tried to follow readme file. But, when I run 'rails db:create', an error is raised;
```

FATAL:  role "hasan" does not exist
Couldn't create 'ror_social_scaffold_development' database. Please check your configuration.
rails aborted!
ActiveRecord::NoDatabaseError: FATAL:  role "hasan" does not exist
Caused by:
PG::ConnectionBad: FATAL:  role "hasan" does not exist

```
I am using;
Postgres version: 10+190ubuntu0.1
Rails version: 5.2.4.1
Ruby version: 2.7.0p0
 
When we are working on our project with my partner, we solved this problem. But, when we were developing this project, we got other errors. I couldn't remember these errors. Again, we spent a long time to solve them.

Let me share [what one of TSE's got](https://github.com/imhilla/facebook-clone/pull/2#pullrequestreview-462933352). But, when we requested feedback, we don't have any problem related to PostgreSQL.

Please, let me know if more information is necessary to define the error that I attached.

**Comment by fatymahmed** [comment]
> Hi @fatymahmed,
> 
> I cloned this repository and tried to follow the readme file. But, when I run 'rails db:create', an error is raised;
> 
> ```
> 
> FATAL:  role "hasan" does not exist
> Couldn't create 'ror_social_scaffold_development' database. Please check your configuration.
> rails aborted!
> ActiveRecord::NoDatabaseError: FATAL:  role "hasan" does not exist
> Caused by:
> PG::ConnectionBad: FATAL:  role "hasan" does not exist
> ```
> 
> I am using;
> Postgres version: 10+190ubuntu0.1
> Rails version: 5.2.4.1
> Ruby version: 2.7.0p0
> 
> When we are working on our project with my partner, we solved this problem. But, when we were developing this project, we got other errors. I couldn't remember these errors. Again, we spent a long time to solve them.
> 
> Let me share [what one of TSE's got](https://github.com/imhilla/facebook-clone/pull/2#pullrequestreview-462933352). But, when we requested feedback, we didn't have any problem related to PostgreSQL.
> 
> Please, let me know if more information is necessary to define the error that I attached.

Hey @ozovalihasan 
The error you mentioned above was because you were setting up PostgreSQL for the first time, it means that you had not created a PostgreSQL user by that name in your database as explained in the [ubuntu PostgreSQL documentation](https://help.ubuntu.com/community/PostgreSQL#Create_database).

**Pull request closed without merging**
