### PR TITLE
Add ERD diagram to docs

### PR DESCRIPTION
**Pull request by ahmadchata**
In this Milestone
- I added an ERD diagram to docs

### CODE REVIEW

**Review by javitocor — CHANGES_REQUESTED** [review]
# STATUS CHANGES REQUIRED 🛑 

Hello! Good job implementing the docs in this project! 👍 
Your diagram looks good and ready to implement it! 💪 
However, we must do some changes in order to get the project approved: ♻️ 
Kindly check my comments below 👇  implement the changes and resubmit your project for a new code review ⏩ 
## Mandatory changes
- Fix the linters in the project, we want to see them always green 🟢 , it is important to pass all linters in order to always open the pull request in a professional way
- Fill up your README file, same here, let this look professional, add a link to your diagram and all the important information needed and that you already done in previous projects!
That's all!
Good luck! 😺

**Comment by ahmadchata** [comment]
## Changes made
- Update README file with an image of ERD
- Fix linter error

**Review by javitocor — APPROVED** [review]
# STATUS APPROVED ⭐ 🥇 

A great job! 👏 
Now you have met all the basic requirements! Congratulations! 💯 👍 
Remember to merge your branch, fill up the completion form 📑  in your dashboard, and you can move into the next milestone 🚀 
Good luck with it! 😃

**Comment by bolah2009** [comment]
@ahmadchata This is the wrong project to open this PR as this is the scaffold repo, not the student repo.

You should open a PR with your branch as the base branch, not the mircroverse branch.
Also, don't forget about GitFlow.

You can edit the PR and change the base branch to your development branch.

I will be closing this PR, I apologize for the inconvenience. 🙂

@javitocor Please take note of this in your future reviews. 🙂

**Pull request closed without merging**
