### PR TITLE
Feature/first milestone

### PR DESCRIPTION
**Pull request by DeliceLydia**
In this first milestone I added :

-  Docs file in the root  directory
-  a screenshot of the ERB file

### CODE REVIEW

**Comment by pointerish** [comment]
Hi @DeliceLydia, I'm pretty sure the PR was not supposed to be created for this repo as this is just a template. The PR must be done on your fork.

I was just looking at this repo and noticed this. I am not a TSE.

**Comment by kobiyoyo** [comment]
Hello @DeliceLydia , I am marking this PR as invalid because its created on Microverse ROR Template,
Kindly create another request from your project when ready.
Regards.

**Comment by DeliceLydia** [comment]
Oooh am so sorry for this let me correct my mistake.
Thank you!

**Comment by uryelah** [comment]
@DeliceLydia    This is the wrong project to open this PR as this is the scaffold repo, not the student repo.

You should open a PR with your branch as the base branch, not the Microverse branch.
Also, don't forget about GitFlow.

You can edit the PR and change the base branch to your development branch.

If you happen to open a PR mistakenly again please close it the moment you notice the mistake.

I will be closing this PR, I apologize for the inconvenience. 🙂

**Comment by DeliceLydia** [comment]
Hello Sarah,

I am so sorry I created a PR by mistake again in the scaffold
but I am trying to close it but I don't see a close option I think am
not allowed to do it.

Please close it for me and sorry for my repeated mistakes am new in
coding it is my first time to work on a forked project.

Sorry for the inconvenience!

Lydia

**Comment by uryelah** [comment]
I closed it already Lydia, it's ok we all make mistakes sometimes 😉

**Pull request closed without merging**
