### PR TITLE
Add EDB diagram

### PR DESCRIPTION
**Pull request by taiwo2**
EDB Diagram showing relationship as a user quest to create/signin,
After login to be able to see all users,posts,comments.
Friendship table having id, sender_id,receiver_id,status,created_at,updated_at.

### CODE REVIEW

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey @taiwo2, 👋🏽 
 **Thank you for the good job you got going on. The ERD is almost perfect.**
Just a few more changes to get it right.

## REQUIRED CHANGES

- [ ] Kindly change the folder name from `doc` to `docs` as requested.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/erd2.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] Please review the usage of `one` and `one and only one` ERD rules.

**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding.

# Reach me on slack for a chitchat 🆘  **Roy Mukuye**

**Comment by uryelah** [comment]
@taiwo2   This is the wrong project to open this PR as this is the scaffold repo, not the student repo.

You should open a PR with your branch as the base branch, not the microverse branch.
Also, don't forget about GitFlow.

You can edit the PR and change the base branch to your development branch.

@mke2111  Please mark PRs with this type of GitFlow mistake and no PR message as invalid, check that first, specially in RoR projects, before starting your review.

I will be closing this PR, I apologize for the inconvenience. 🙂

**Comment by taiwo2** [comment]
I Don't really understand this, others student did the same and no problem why are you saying this. i don't understand

**Review by umairarshadbutt — COMMENTED** [review]
# Status: REQUIRED CHANGES :warning: 

**Hi @taiwo2 **
There is a problem with your git-flow. Your pull request is from `taiwo2:feature-doc` to `microverseinc:master` . It should be from your branch `feature-doc` to your development branch. 
Kindly read about git-flow [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/) and fix your project by creating another repo and following the git-flow guidelines
I am going to mark this project as invalid so when you fix the issue just submit another code review request.
##

 **If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request closed without merging**
