### PR TITLE
Feature 2

### PR DESCRIPTION
**Pull request by Sick-Carlito**
Please have a look at my project and help me check if all the requirements are implemented. The project is supposed to allow a user to create a post, make comments and like a post. A user is also supposed to send and receive friend requests where a user can cancel or accept another user's requests.

### CODE REVIEW

**Comment by samgaco** [comment]
Hi @Sick-Carlito 

I can see right now even if two users are not friends they can see each other's posts, and that shouldn't be happening. The users are also not able to decline a friendship. So the following two requirements should be implemented:

- [ ] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))  


I also have seen your tests are not covering all the models and there are no integration tests. Please implement those as well since it will be something useful for you to learn moving on.

- [ ] **Add tests** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png)  from  [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

For this part, I would recommend the usage of [factory bot](https://github.com/thoughtbot/factory_bot) which is a nice replacement for the rails default fixtures which work well with RSpec

this part of the test you have implemented:

```
    if first_user.valid?
      first_user.save
      second_user = User.new(name: 'Foobar', email: 'foo1@bar.com', password: 'foobar')
      second_user.save
    else
      first_user = User.first
      second_user = User.second
    end
```

could be structured into another test 

and this line with factory bot could go from:

```
    first_user = User.new(name: 'Foobar', email: 'foo@bar.com', password: 'foobar')
```

to something cleaner like

`let(:user) { build(:user) }
`

-------------------

Moving on :arrow_down: 

* **[For your next code review requests]**  Use meaningful names for your Pull Requests
* **[For your next code review requests]**  Add a short summary of changes in Pull Request description

----------------

* ###### STATUS OF THE MILESTONE: REQUESTED CHANGES :stop_sign:

**Comment by Sick-Carlito** [comment]
Oh sorry, i forgot abut the PR description.

**Comment by Sick-Carlito** [comment]
Sorry guys, i couldn't open a new PR. However, i implemented a few changes and according to the requirements from the last feedback. A user can now accept or reject friend requests and i also added a few models tests.

**Comment by Sick-Carlito** [comment]
my side, doing git branch -a lists all the branches i have in my local repo.

**Comment by Sick-Carlito** [comment]
Sure.

**Comment by Oluwadamilareolusakin** [comment]
# User Model
screenshot
screenshot
screenshot
screenshot

**Comment by Sick-Carlito** [comment]
Please help me point out these key implementations sir, I can't find any that I've not yet implemented. I was supposed to add a few functionalities and add a few more unit tests. I'd appreciate any help. thanks.

**Comment by Sick-Carlito** [comment]
In the meantime, I'm gonna go ahead and submit for another code review. If you can find any unimplemented features, let me know. Thanks.

**Comment by Sick-Carlito** [comment]
Thanks bro.

**Comment by Sick-Carlito** [comment]
Hello guys, my project has been approved but i can't find the merge button to merge commits from my branch. Any ideas as to why this might be happening? Thanks.

**Pull request closed without merging**
