### PR TITLE
Milestone 5:- Friendship v1

### PR DESCRIPTION
**Pull request by hemant-soni-vst-au4**
In this milestone, we applied all our knowledge on the ActiveRecord relationship to create a Friendship between users.

## Project Requirments
- Create a model with associations and all requested features for friendships

## As a guest user:

 - I want to be able to create an account/log in.
 - I can see only the “Sign in” and “Sign out” page.

## As a logged-in user:

 - I want to be able to see all the users list.
 - I want to be able to see selected user pages with their user name and all posts written by them (the most recent posts on the top).
 - I want to be able to send a friendship invitation.
 - I want to see a button “Invite to friendship” next to the name of the user who is not my friend yet - on both users’ list and single-user page.
 - I want to be able to see pending friendship invitations sent to me from other users.
 - I want to be able to accept or reject friendships invitation.
 - I want to be able to create new posts (text only).
 - I want to be able to like/dislike posts (but I can like a single post only once).
 - I want to be able to add comments to posts.

### CODE REVIEW

**Comment by uryelah** [comment]
Hi **Hemant Soni & Fow Fow Aranibar**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job with most of the fixes, you missed one but you got this! 💪 

# Required Changes 🏗️ 🐛 💡

- [ ] Your Posts#index is only sending the posts from the current_user to the view. It should also get the posts created by the user friends. Make sure to update your `timeline_posts` method.

-----

 **Kindly fix the pointed out issues before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by uryelah** [comment]
Good job! You implemented the request in a very elegant way.

-------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**


---------

    
    
**Keep being awesome devs and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by hemant-soni-vst-au4** [comment]
thanxs for feedback

**Comment by bolah2009** [comment]
@hemant-soni-vst-au4 This is the wrong project to open this PR as this is the scaffold repo, not the student repo.

You should open a PR with your branch as the base branch, not the mircroverse branch.
Also, don't forget about GitFlow.

You can edit the PR and change the base branch to your development branch.

I will be closing this PR, I apologize for the inconvenience. 🙂

@uryelah @maelfosso Please this PR should have been marked as invalid, kindly take note in future CRR. 🙏

**Pull request closed without merging**
