### PR TITLE
Ror-Social-Scaffold

### PR DESCRIPTION
**Pull request by dasileker**
### Social-scaffold

_Added the ERD image_

-  created the database PostgreSQL

- migrated the database

- added the ERD image in the folder App/assets/images.

### CODE REVIEW

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 
Your ERD is not structured well please return back and read more about ERD, and also consider the comments below.
:point_down: :point_down: :point_down: :point_down:

## Required Changes :red_circle::

- [ ] no need to put your ERD inside the `app/` directory put it inside a `docs/` directory and later add it to your readme.

- [ ] you are messing the like table please add one.

- [ ]  Please return back and read about ERD cause it seems like you didn't quite understand it. you will say why ok. In Entities, we are not supposed to have method names in them we should have only name fields that we are going to use on our migration.

### Please make all the requested changes before you ask for another code review.
## Happy Coding :tophat: 
_If you have any question or need help don't hesitate to contact me on slack_
## Zakariae El Mejdki.

**Comment by dasileker** [comment]
thanks done

**Comment by mimipeshy** [comment]
### STATUS : APPROVED :partying_face: 
Hey, team @dasileker I think you have understood the basics of the ERD. This project is therefore approved. Go ahead and merge. Happy Coding :technologist: 

Regards
Peris Ndnau

**Comment by elmejdki** [comment]
ooooh is that you?? hhh how are you @dasileker, great job you made it to the ror project keep going

**Comment by elmejdki** [comment]
@dasileker watch out where you are merging, you are merging the wrong repository close this one and create another one that merges to your repo.

**Comment by uryelah** [comment]
@dasileker     This is the wrong project to open this PR as this is the scaffold repo, not the student repo.

You should open a PR with your branch as the base branch, not the Microverse branch.
Also, don't forget about GitFlow.

You can edit the PR and change the base branch to your development branch.

If you happen to open a PR mistakenly again please close it the moment you notice the mistake.

@elmejdki & @mimipeshy please remember to double check if a the PR, specially in this project, is made into the correct destination branch.
It should point to the main branch of the student's repo, if it points to the main forked repo branch it should be **marked as invalid** and not reviewed.

I will be closing this PR, I apologize for the inconvenience. 🙂

**Comment by dasileker** [comment]
Hello, For sorry for the inconvenience I did cause, for that matter I did open a PR in my ( first_milstone_docs_erd ) branch as a compare to  the development branch, but I did found when I did pull the request it was  directed to the initial repo I did fork , I didn’t know how that happened I checked but I couldn’t find any answer till you sent this email. Again sorry for any inconvenience I did cause. Thank you  I will be more vigilante next time, I will double check before I will do anything. Provenance : Courrier pour Windows 10 De : Sarah ChamorroEnvoyé le :mercredi 27 janvier 2021 12:32À : microverseinc/ror-social-scaffoldCc : zerradi amine; MentionObjet :Re: [microverseinc/ror-social-scaffold] Ror-Social-Scaffold (#263) @dasileker This is the wrong project to open this PR as this is the scaffold repo, not the student repo.You should open a PR with your branch as the base branch, not the Microverse branch.Also, don't forget about GitFlow.You can edit the PR and change the base branch to your development branch.If you happen to open a PR mistakenly again please close it the moment you notice the mistake.@elmejdki & @mimipeshy please remember to double check if a the PR, specially in this project, is made into the correct destination branch.It should point to the main branch of the student's repo, if it points to the main forked repo branch it should be marked as invalid and not reviewed.I will be closing this PR, I apologize for the inconvenience. 🙂—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.  
	
      
		Garanti sans virus. www.avg.com

**Comment by dasileker** [comment]
Thanks man . Provenance : Courrier pour Windows 10 De : Zakariae El MejdkiEnvoyé le :mercredi 27 janvier 2021 12:20À : microverseinc/ror-social-scaffoldCc : zerradi amine; MentionObjet :Re: [microverseinc/ror-social-scaffold] Ror-Social-Scaffold (#263) ooooh is that you?? hhh how are you @dasileker, great job you made it to the ror project keep going—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.  
	
      
		Garanti sans virus. www.avg.com

**Pull request closed without merging**
